# =============================================================================
# NOTE:
#   * Plugins are installed by the `github-pages` gem. So they are not
#     explicitly listed in Gemfile. See
#     https://pages.github.com/versions/ for available plugins.
#     Here in _config.yml, we still need to list the plugins we want to use.
# =============================================================================

# basic infor for GitHub pages
domain: quantom-collab.github.io
baseurl: "/website-prototype-quant" # intentionally left blank

# markdown renderer
markdown: kramdown

# jekyll plugins that we want to use
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# jekyll-seo-tag condfigs and site meta
title: ePIC Collaboration
tagline: ePIC Collaboration
description: ePIC Collaboration
author: ePIC Collaboration
logo: /assets/img/logo.png
locale: en_US

# grouping different types of posts
collections:
  # folder _news
  news:
    output: true
  # folder _pages
  pages:
    output: true
    permalink: /:name

# default key-value pairs in the front matter for each category
defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"
      author: "QuantOm"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"


# SCSS compiler config
sass:
  style: compressed

# things not to include in the `_site` folder
exclude:
  - "template"
  - "old"
  - ".sass-cache"
  - ".jekyll-cache"
  - "gemfiles"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle"
  - "vendor/cache"
  - "vendor/gems"
  - "vendor/ruby"
  - "README.md"
